### ISSUE TITLE
Rarbg links not found

### ISSUE THREAD

**Issue by gattomatto69** [mancuniancol/script.pulsar.rarbg-mc#1]
Hi there,
I don't know if this is the best place to post this. I'm using w/o any problems other providers from you, great job BTW. For RARBG I can't get it to work: it always result in "No links were found". I'm using version 3.0.2 on Kodi 14.2. I even tried changing the url to rarbg.to w/o luck.
Hope you can help me.
Thanks

**Comment by mancuniancol** [comment]
Thanks for your feedback. I will check that.  Some place changed their pages.  Sometimes, I think to make harder to get the information from the providers.  But, Pulsar 0.6.1 allows to extend the time-out configuration, then it will be easy to jump those restriction. I am little busy lately, but I will release a fix asap.

**Comment by rarbg** [comment]
@mancuniancol 
http://torrentapi.org/apidocs.txt
:) Working on v2 of the , but you can easily implement v1 because its 90% compatible.
Ill also add you to the project

**Comment by mancuniancol** [comment]
@rarbg, I will check this weekend your proyect.  It will be a pleasure to help.

**Comment by mancuniancol** [comment]
NOw it is working, but you need to use the default settings to get the new url

**Comment by gattomatto69** [comment]
I uninstalled the provider and downloaded it again. I also reset it to default, still not working. What am I missing ?
Thanks!

**Comment by mancuniancol** [comment]
Could you give me access to your log, please?  You can use pastebin.com
