### ISSUE TITLE
late night shows search 

### ISSUE THREAD

**Issue by co5mo** [mancuniancol/script.pulsar.rarbg-mc#2]
hi mancuniancol

your providers do not work for some late night shows because scene uses dates and not S0XE0X format

Stephen.Colbert.2015.09.08.George.Clooney.INTERNAL.720p.HDTV.x264

I would like to watch stephen colbert and it cant be found using any provider is there a change to change that?

isnt there a way to browse all content from some providers? it would solve this

thanks.

**Comment by mancuniancol** [comment]
Yes, you can use EZTV2kd or eztvapi2kd, it doesn't required providers. 
The problem is not the provider, it is Pulsar's format. It is nothing I can do.
